services:
  - type: web
    name: cvdtt-backend
    env: docker
    repo: https://github.com/td-29th02/CVDTT_Deploy
    branch: main
    rootDir: cafemanagement
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /

  - type: web
    name: cvdtt-frontend
    env: docker
    repo: https://github.com/td-29th02/CVDTT_Deploy
    branch: main
    rootDir: cafe_fontend
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /
